[package]
name = "高等数学习题册上册"
version = "1.0.0"
authors = ["李锋", "阳振辉", "郑和柏"]
entrypoint = "index.typ"

[template]
title = "高等数学习题册（上册）"
description = "与同济大学数学系编写的《高等数学(第七版)》相配套的教学辅助书"

# 字体配置
[fonts]
LXGW WenKai = "LXGWWenKai-Regular.ttf"
STKaiti = "STKaiti.ttf"